[2017-10-27 10:44:22,120 - ERROR : ResultParser.py:116 - ValidateConfigf() ] No line_type in  vul_prog.stdin : XXXXX : 4
